#!/bin/bash

# Create main.h
cat <<EOF > main.h
#ifndef MAIN_H
#define MAIN_H

int _putchar(char c);
int _atoi(char *s);

#endif /* MAIN_H */
EOF

# Create _putchar.c
cat <<EOF > _putchar.c
#include <stdio.h>
#include "main.h"

/**
 * _putchar - writes the character c to stdout
 * @c: The character to print
 *
 * Return: On success 1.
 * On error, -1 is returned, and errno is set appropriately.
 */
int _putchar(char c)
{
    return (write(1, &c, 1));
}
EOF

# Create 0-whatsmyname.c
cat <<EOF > 0-whatsmyname.c
#include <stdio.h>
#include "main.h"

/**
 * main - prints the name of the program
 * @argc: number of arguments
 * @argv: array of arguments
 *
 * Return: Always 0 (Success)
 */
int main(int argc __attribute__((unused)), char *argv[])
{
    printf("%s\n", *argv);
    return (0);
}
EOF

# Create 1-args.c
cat <<EOF > 1-args.c
#include <stdio.h>
#include "main.h"

/**
 * main - print the number of arguments passed to the program
 * @argc: number of arguments
 * @argv: array of arguments
 *
 * Return: Always 0 (Success)
 */
int main(int argc, char *argv[])
{
    (void) argv; /*Ignore argv*/
    printf("%d\n", argc - 1);
    return (0);
}
EOF

# Create 2-args.c
cat <<EOF > 2-args.c
#include <stdio.h>
#include "main.h"

/**
 * main - prints all arguments it receives
 * @argc: number of arguments
 * @argv: array of arguments
 *
 * Return: Always 0 (Success)
 */
int main(int argc, char *argv[])
{
    int i;

    for (i = 0; i < argc; i++)
    {
        printf("%s\n", argv[i]);
    }

    return (0);
}
EOF

# Create 3-mul.c
cat <<EOF > 3-mul.c
#include <stdio.h>
#include "main.h"

/**
 * _atoi - converts a string to an integer
 * @s: string to be converted
 *
 * Return: the int converted from the string
 */
int _atoi(char *s)
{
    int i, d, n, len, f, digit;

    i = 0;
    d = 0;
    n = 0;
    len = 0;
    f = 0;
    digit = 0;

    while (s[len] != '\0')
        len++;

    while (i < len && f == 0)
    {
        if (s[i] == '-')
            ++d;

        if (s[i] >= '0' && s[i] <= '9')
        {
            digit = s[i] - '0';
            if (d % 2)
                digit = -digit;
            n = n * 10 + digit;
            f = 1;
            if (s[i + 1] < '0' || s[i + 1] > '9')
                break;
            f = 0;
        }
        i++;
    }

    if (f == 0)
        return (0);

    return (n);
}

/**
 * main - multiplies two numbers
 * @argc: number of arguments
 * @argv: array of arguments
 *
 * Return: 0 (Success), 1 (Error)
 */
int main(int argc, char *argv[])
{
    int result, num1, num2;

    if (argc < 3 || argc > 3)
    {
        printf("Error\n");
        return (1);
    }

    num1 = _atoi(argv[1]);
    num2 = _atoi(argv[2]);
    result = num1 * num2;

    printf("%d\n", result);

    return (0);
}
EOF

# Create 4-add.c
cat <<EOF > 4-add.c
#include <stdio.h>
#include <stdlib.h>
#include <ctype.h>
#include <string.h>

/**
 * check_num - check - string there are digit
 * @str: array str
 *
 * Return: Always 0 (Success)
 */
int check_num(char *str)
{
    /*Declaring variables*/
    unsigned int count;

    count = 0;
    while (count < strlen(str)) /*count string*/
    {
        if (!isdigit(str[count])) /*check if str there are digit*/
        {
            return (0);
        }
        count++;
    }
    return (1);
}

/**
 * main - Print the name of the program
 * @argc: Count arguments
 * @argv: Arguments
 *
 * Return: Always 0 (Success)
 */
int main(int argc, char *argv[])
{
    /*Declaring variables*/
    int count;
    int str_to_int;
    int sum = 0;

    count = 1;
    while (count < argc) /*Goes through the whole array*/
    {
        if (check_num(argv[count]))
        {
            str_to_int = atoi(argv[count]); /*ATOI --> convert string to int*/
            sum += str_to_int;
        }
        /*Condition if one of the number contains symbols that are not digits*/
        else
        {
            printf("Error\n");
            return (1);
        }
        count++;
    }

    printf("%d\n", sum); /*print sum*/

    return (0);
}
EOF

# Create 100-change.c
cat <<EOF > 100-change.c
#include <stdio.h>
#include <stdlib.h>
#include "main.h"

/**
 * main - prints the minimum number of coins to
 * make change for an amount of money
 * @argc: number of arguments
 * @argv: array of arguments
 *
 * Return: 0 (Success), 1 (Error)
 */
int main(int argc, char *argv[])
{
    int num, j, result;
    int coins[] = {25, 10, 5, 2, 1};

    if (argc != 2)
    {
        printf("Error\n");
        return (1);
    }

    num = atoi(argv[1]);
    result = 0;

    if (num < 0)
    {
        printf("0\n");
        return (0);
    }

    for (j = 0; j < 5 && num >= 0; j++)
    {
        while (num >= coins[j])
        {
            result++;
            num -= coins[j];
        }
    }

    printf("%d\n", result);
    return (0);
}
EOF

echo "Files created successfully!"

